server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    show-sql: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  hibernate-orm:
    sql-load-script: data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    tags-sorter: alpha
    operations-sorter: alpha
    persist-authorization: true
    display-request-duration: true

template-id:
  account-statement: AccountStatement

cache:
  expire-hours: 24